### ISSUE TITLE
Permanent startup errors in Windows Events

### ISSUE THREAD

**Issue by vkoulich** [handruin/spdif-ka#36]
Every time I start my machine, I'm getting the following two errors in Windows Events, always together (after one another):

**Event 1026**

Application: SPDIFKA.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Configuration.XmlUtil..ctor(System.IO.Stream, System.String, Boolean, System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.ClientConfigurationSystem.OnConfigRemoved(System.Object, System.Configuration.Internal.InternalConfigEventArgs)

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationManager.PrepareConfigSystem()
   at System.Configuration.ConfigurationManager.get_AppSettings()
   at System.Windows.Forms.DpiHelper.Initialize()

Exception Info: System.TypeInitializationException
   at SPDIFKA.SPDIFKAGUI..ctor()
   at SPDIFKA.SPDIFKA.Main()

**and Event 1000 (100)**

Faulting application name: SPDIFKA.exe, version: 1.4.0.0, time stamp: 0x58ca0a39
Faulting module name: KERNELBASE.dll, version: 6.1.7601.24150, time stamp: 0x5b0cbc65
Exception code: 0xe0434352
Fault offset: 0x000000000001a06d
Faulting process id: 0x1214
Faulting application start time: 0x01d417136f03ace5
Faulting application path: C:\Program Files (x86)\SPDIFKA\SPDIFKA.exe
Faulting module path: C:\Windows\system32\KERNELBASE.dll
Report Id: ad787c5c-8306-11e8-a49f-c8600017ee38

The SPDIF-KA seems to be running though after that, but I wonder why this is happening and if I should be concerned about it. Of course, it's not nice that it's filling my Events log, but ... I can live with that if it doesn't indicate some malfunction. Please advise.

**Comment by xdanik** [comment]
I had similar issue - In my case SPDIFKA logged this error and immediately crashed.
Resolved by deleting config file in `C:\Users\%username%\AppData\Local\handruin.com` - the file got propadly corrupted during recent BSOD.
